kind: Pod
apiVersion: v1
metadata:
    name: test-secret-provider
    labels:
      aadpodidbinding: grouper-pod-identity
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: GROUPER_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: grouper-secrets
              key: url
        - name: GROUPER_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: grouper-secrets
              key: username
        - name: GROUPER_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grouper-secrets
              key: password
      resources: {}
      volumeMounts:
        - name: azurekeyvault
          mountPath: /mnt/secrets-store
          readOnly: true
  volumes:
    - name: azurekeyvault
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: grouper-secrets-provider # this is the name of your SecretProviderClass